### ISSUE TITLE
will it take extra space?

### ISSUE THREAD

**Issue by Ex-Communicad0** [TechExhibeo/gdrive-backup-cyberpanel#3]
Hello,

it will just clone the site folder? Or it will first zip the site folder then backup to drive?

If it will create zip it will take more space

Can you please clear this?

**Comment by xaksh** [comment]
@TechExhibeo Can you please answer this?

**Comment by TechExhibeo** [comment]
> Hello,
> 
> it will just clone the site folder? Or it will first zip the site folder then backup to drive?
> 
> If it will create zip it will take more space
> 
> Can you please clear this?

Yes script will first create archive and then upload to Google drive
