### ISSUE TITLE
Looks like this code doesn't work on centos 8. 

### ISSUE THREAD

**Issue by levanthuc** [TechExhibeo/gdrive-backup-cyberpanel#4]
I use centos 8, id doesn't have ssmtp
Looks like this code doesn't work on centos 8. 
Can you help me!

**Comment by xaksh** [comment]
@TechExhibeo Can we check this and reply?

**Comment by TechExhibeo** [comment]
CentOS 8 is EOL. 

You may try if it helps or compile ssmtp from source.
https://www.reddit.com/r/linuxadmin/comments/dva5gj/comment/fk2ffw1/
